# Generated by Django 3.1.7 on 2021-02-22 04:14

from django.db import migrations, models
import echomain.models
import echomain.storage


class Migration(migrations.Migration):

    dependencies = [
        ('echomain', '0002_auto_20210222_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=echomain.storage.OverwriteStorage(), upload_to=echomain.models.get_path_and_name),
        ),
    ]
